services:
  - type: web
    name: criptopedia-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: YOUTUBE_API_KEY
        value: AIzaSyDNphleDorA8eYwvZ9KFLgb7_5KKad-8Bk
      - key: FRONTEND_URL
        value: https://criptopedia-universal.netlify.app